apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cubbit-slideshow.fullname" . }}-secret
  labels:
    {{- include "cubbit-slideshow.labels" . | nindent 4 }}
type: Opaque
data:
  # Private S3 configuration
  S3_REGION: {{ .Values.cubbit.S3_REGION | b64enc }}
  S3_ACCESS_KEY_ID: {{ .Values.cubbit.S3_ACCESS_KEY_ID | b64enc }}
  S3_SECRET_ACCESS_KEY: {{ .Values.cubbit.S3_SECRET_ACCESS_KEY | b64enc }}
  MULTIPART_THRESHOLD: {{ .Values.cubbit.MULTIPART_THRESHOLD | b64enc }}
  # This endpoint is used both on server and client side
  S3_ENDPOINT: {{ .Values.cubbit.S3_ENDPOINT | b64enc }}
  # Settings authentication
  AUTH_USERNAME: {{ .Values.auth.username | b64enc }}
  AUTH_PASSWORD: {{ .Values.auth.password | b64enc }}
  JWT_SECRET: {{ .Values.auth.jwtSecret | b64enc }}
