{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cubbit-slideshow.fullname" . }}
  labels:
    {{- include "cubbit-slideshow.labels" . | nindent 4 }}
type: Opaque
data:
  s3-endpoint: {{ .Values.s3.endpoint | b64enc | quote }}
  s3-access-key-id: {{ .Values.s3.accessKeyId | b64enc | quote }}
  s3-secret-access-key: {{ .Values.s3.secretAccessKey | b64enc | quote }}
  {{- if .Values.auth.adminPassword }}
  admin-password: {{ .Values.auth.adminPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.jwtSecret }}
  jwt-secret: {{ .Values.auth.jwtSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.webhook.secret }}
  webhook-secret: {{ .Values.webhook.secret | b64enc | quote }}
  {{- end }}
  {{- if .Values.webhooks }}
  webhooks: {{ .Values.webhooks | b64enc | quote }}
  {{- end }}
{{- end }}
