# Default values for cubbit-slideshow helm chart
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
    repository: cubbit/slideshow-demo
    pullPolicy: Always
    tag: 'latest'

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

service:
    type: ClusterIP
    port: 80
    targetPort: 3000

ingress:
    enabled: true
    className: 'nginx'
    annotations:
        kubernetes.io/ingress.class: nginx
        # cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
        - host: slideshow.local
          paths:
              - path: /
                pathType: Prefix
    tls:
        - secretName: slideshow-tls
          hosts:
              - slideshow.local

resources:
    limits:
        cpu: 500m
        memory: 512Mi
    requests:
        cpu: 100m
        memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: {}

# Application configuration
# Set logging level - defaults to "error", for verbose logs use "verbose" or "debug"
loggingLevel: 'info' # Options: error, warn, info, debug, verbose

auth:
    username: 'admin' # Change this in production!
    password: 'admin' # Change this in production!
    jwtSecret: 'change-this-to-a-random-secure-string-in-production' # Change this in production!

# Cubbit slideshow specific configuration
cubbit:
    # Public environment variables
    S3_BUCKET_NAME: 'slideshow'
    MAX_FILE_SIZE: '10485760' # 10MB in bytes
    SLIDESHOW_SPEED_S: '200' # Speed of slideshow animation in seconds
    MIN_COUNT_FOR_MARQUEE: '6' # Minimum number of photos needed to start carousel animation

    # Private environment variables (will be stored in a Secret)
    S3_REGION: 'eu-central-1'
    S3_ACCESS_KEY_ID: ''
    S3_SECRET_ACCESS_KEY: ''
    MULTIPART_THRESHOLD: '5242880' # 5MB in bytes
    S3_ENDPOINT: ''
